In [29]:
import numpy as np
T1= 45# theta 1 angle in degrees
T2 = 45 # theta 2 angle in degrees
T1 = (T1/180.0)*np.pi # theta 1 in radian
T2 = (T2/180.0)*np.pi # theta 2 in radian
R0_1 = [[np.cos(T1), -np.sin(T1), 0],
       [np.sin(T1), np.cos(T1), 0], 
       [0,0,1]]
R1_2= [[np.cos(T2), -np.sin(T2), 0],
      [np.cos(T2), np.sin(T2), 0],
      [0,0,1]]
R0_2= np.dot(R0_1, R1_2)
print(R0_2)
a1 = 5 # link length a1
a2 = 6 # link length a2
a3 = 5.5 # link length a3
a4 = 5.5 # link length a4

[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


In [30]:
d0_1 = [[a2*np.cos(T1)], 
       [a2*np.sin(T1)],
       [a1]]
d1_2 = [[a4*np.cos(T2)], 
       [a4*np.sin(T2)],
       [a3]]
    
print(np.matrix(d1_2))

[[3.8890873]
 [3.8890873]
 [5.5      ]]


In [31]:
H0_1 = np.concatenate((R0_1,d0_1), 1)
H0_1 = np.concatenate((H0_1,[[0,0,0,1]]),0)
print(np.matrix(H0_1))

[[ 0.70710678 -0.70710678  0.          4.24264069]
 [ 0.70710678  0.70710678  0.          4.24264069]
 [ 0.          0.          1.          5.        ]
 [ 0.          0.          0.          1.        ]]


In [32]:
 H1_2 = np.concatenate((R1_2,d1_2), 1)
H1_2 = np.concatenate((H1_2,[[0,0,0,1]]),0)
#print(np.matrix(H1_2))
H0_2 = np.dot(H0_1, H1_2)
print(np.matrix(H0_2)) 

[[ 0.         -1.          0.          4.24264069]
 [ 1.          0.          0.          9.74264069]
 [ 0.          0.          1.         10.5       ]
 [ 0.          0.          0.          1.        ]]
